name: CI
on: [push]
jobs:
  access:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dump Access views
        run: cscript //nologo utils\dump_access_views.vbs utils\sample.accdb >views.sql
      - name: Diff the output
        run: compare-object (get-content utils\sample_views.sql) (get-content views.sql)
